services:
  stats-server:
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:16.1

  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      stats-client:
        condition: service_healthy

  ewm-db:
    image: postgres:16.1
