version: '3.8'

services:
  stats-server:
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 8
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://stats-db:5432/stats?connectTimeout=5000"
      SPRING_DATASOURCE_USERNAME: "dbuser"
      SPRING_DATASOURCE_PASSWORD: "12345"
      SPRING_LIQUIBASE_ENABLED: "true"
    restart: unless-stopped

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "stats"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - stats-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d stats"]
      interval: 5s
      timeout: 5s
      retries: 15

  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      stats-server:
        condition: service_healthy
    environment:
      STATS_SERVICE_URL: "http://stats-server:9090"

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - main-data:/var/lib/postgresql/data

volumes:
  stats-data:
  main-data: