-- liquibase formatted sql

-- changeset belov:001-create-locations
CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

-- changeset belov:002-alter-events dependsOn:001-create-locations
ALTER TABLE events
    ADD COLUMN IF NOT EXISTS annotation TEXT,
    ADD COLUMN IF NOT EXISTS title VARCHAR(125),
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS confirmed_requests BIGINT,
    ADD COLUMN IF NOT EXISTS created_on TIMESTAMP,
    ADD COLUMN IF NOT EXISTS event_date TIMESTAMP,
    ADD COLUMN IF NOT EXISTS paid BOOLEAN,
    ADD COLUMN IF NOT EXISTS participant_limit BIGINT,
    ADD COLUMN IF NOT EXISTS published_on TIMESTAMP,
    ADD COLUMN IF NOT EXISTS request_moderation BOOLEAN,
    ADD COLUMN IF NOT EXISTS category_id BIGINT,
    ADD COLUMN IF NOT EXISTS initiator_id BIGINT,
    ADD COLUMN IF NOT EXISTS location_id BIGINT,
    ADD COLUMN IF NOT EXISTS state VARCHAR(21),
    ADD COLUMN IF NOT EXISTS views BIGINT,
    ADD CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES "categories" (id),
    ADD CONSTRAINT fk_events_location FOREIGN KEY (location_id) REFERENCES "locations" (id);